### ISSUE TITLE
Problematic Word doc

### ISSUE THREAD

**Issue by russurquhart1** [jkr/pandoc#6]
Hi Jesse,

I've attached a MUCH smaller word docx file for you to look at. This document is made up of only those issues in the prior docx file, that do not convert properly. My target output format is DocBook and also ASCIIDoc,  from Pandoc. (The only specific issue with the first table in the file, is that, when converted to ASCIIDoc, the entry that spans the columns, COULD be implemented in ASCIIDoc, but probably isn't.)

The <Note> text that follows this, with a soft return after it, causes the generation of a literallayout element instead of an expected para element.

The bulleted items that follow this, do not come across as bulleted items, but as para elements.

The table that follows this, entries in cells 2,2 and 3,2 come over empty.

The two <Note> text para's that follow this table: the first Note item does not come across, only the second one does.

I'll try and send you the word doc as well as the generated docbook.xml file.

**Comment by jkr** [comment]
Russ --

Thanks for posting this here. Still not ideal: there are five separate bugs here, so it's hard to know how to open or close this. That being said:

### 1

> My target output format is DocBook and also ASCIIDoc, from Pandoc. (The only specific issue with the first table in the file, is that, when converted to ASCIIDoc, the entry that spans the columns, COULD be implemented in ASCIIDoc, but probably isn't.)

Pandoc doesn't have multi-column tables, I believe. See a recent thread on the mailing list about it.

### 2 

> The text that follows this, with a soft return after it, causes the generation of a literallayout element instead of an expected para element.

That's an issue for the docbook writer. I don't know much about docbook, but I assume that's how it currently treats soft-linebreaks? In any case, since that's about the docbook writer, it should be a different issue. The internal pandoc representation looks as expected.

### 3 

> The bulleted items that follow this, do not come across as bulleted items, but as para elements.

This is currently an open issue about list environments being defined in a different place. I was just addressing this earlier this week (I wonder if word changed its MO on lists.) In any case, I'm going to open up a separate issue about this myself, since I'm already starting to work on it. It isn't easy.

### 4

> The table that follows this, entries in cells 2,2 and 3,2 come over empty.

Fixed in current development version.

### 5 

> The two text para's that follow this table: the first Note item does not come across, only the second one does.

Fixed in development version.

******

So I'm going to close this for now. The one thing that is still an issue in the writer is a larger problem, that I will post on its own, with more details.

**Comment by jkr** [comment]
Just a note to add that # 3 above is now fixed in development version.

**Comment by russurquhart1** [comment]
Is there a time frame for the release of this or is there a way we could test the dev version?


Thanks,


Russ

**Comment by jkr** [comment]
I don't know about the time frame for release. You can always test the
dev version by building it -- do you have a haskell compiler?

**Comment by russurquhart1** [comment]
I'm not sure if i do for my windows machine at work. Other than that, is there anything else needed to make an executable for windows? I don't have the windows sdk or anything like that.

**Comment by jkr** [comment]
Not sure, I've never built it on windows. But I think you can download
the Haskell platform, and then it should be like for any other platform.

**Comment by russurquhart1** [comment]
OK, i'll give it a try!


Thanks


Russ

**Comment by jkr** [comment]
I just noticed that in the pandoc source dir, there's a windows batch
script called `make-windows-installer.bat`. Maybe that will work?

**Comment by russurquhart1** [comment]
I was going to try it using git as mentioned in the INSTALL file. Should i get your dev from jkr/pandoc or from jgm/pandoc?
 
 
 
 
On 02/19/15, Jesse Rosenthal<notifications@github.com> wrote:
 
I just noticed that in the pandoc source dir, there's a windows batch
script called `make-windows-installer.bat`. Maybe that will work? 

russurquhart1 <notifications@github.com> writes:

> OK, i'll give it a try!
>
>
> Thanks
>
>
> Russ
>
>
> On Thu, Feb 19, 2015 at 06:43:03AM -0800, Jesse Rosenthal wrote:
>> Not sure, I've never built it on windows. But I think you can download
>> the Haskell platform, and then it should be like for any other platform.
>> 
>> russurquhart1 <notifications@github.com> writes:
>> 
>> > I'm not sure if i do for my windows machine at work. Other than that, is there anything else needed to make an executable for windows? I don't have the windows sdk or anything like that.
>> >
>> >
>> >
>> > On Thu, Feb 19, 2015 at 06:29:30AM -0800, Jesse Rosenthal wrote:
>> >> I don't know about the time frame for release. You can always test the
>> >> dev version by building it -- do you have a haskell compiler?
>> >> 
>> >> russurquhart1 <notifications@github.com> writes:
>> >> 
>> >> > Is there a time frame for the release of this or is there a way we could test the dev version?
>> >> >
>> >> >
>> >> > Thanks,
>> >> >
>> >> >
>> >> > Russ
>> >> >
>> >> >
>> >> > On Wed, Feb 18, 2015 at 10:10:32PM -0800, Jesse Rosenthal wrote:
>> >> >> Just a note to add that # 3 above is now fixed in development version.
>> >> >> 
>> >> >> ---
>> >> >> Reply to this email directly or view it on GitHub:
>> >> >> https://github.com/jkr/pandoc/issues/6#issuecomment-75003792
>> >> >
>> >> >
>> >> > ---
>> >> > Reply to this email directly or view it on GitHub:
>> >> > https://github.com/jkr/pandoc/issues/6#issuecomment-75058576
>> >> 
>> >> 
>> >> ---
>> >> Reply to this email directly or view it on GitHub:
>> >> https://github.com/jkr/pandoc/issues/6#issuecomment-75060293
>> >
>> >
>> > ---
>> > Reply to this email directly or view it on GitHub:
>> > https://github.com/jkr/pandoc/issues/6#issuecomment-75061412
>> 
>> 
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/jkr/pandoc/issues/6#issuecomment-75062539
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkr/pandoc/issues/6#issuecomment-75063321


?

**Comment by jkr** [comment]
Always from jgm/pandoc. Mine is just there to store branches while I'm
switching computers, or to try stuff out.

**Comment by russurquhart1** [comment]
Ok, i'll do that then. 

btw, i have haskell 2013.2.0.0, will that work, or do i need a later version?


 
On 02/19/15, Jesse Rosenthal<notifications@github.com> wrote:
 
Always from jgm/pandoc. Mine is just there to store branches while I'm
switching computers, or to try stuff out.

russurquhart1 <notifications@github.com> writes:

> I was going to try it using git as mentioned in the INSTALL file. Should i get your dev from jkr/pandoc or from jgm/pandoc?
> 
> 
> 
> 
> On 02/19/15, Jesse Rosenthal<notifications@github.com> wrote:
> 
> I just noticed that in the pandoc source dir, there's a windows batch
> script called `make-windows-installer.bat`. Maybe that will work? 
>
> russurquhart1 <notifications@github.com> writes:
>
>> OK, i'll give it a try!
>>
>>
>> Thanks
>>
>>
>> Russ
>>
>>
>> On Thu, Feb 19, 2015 at 06:43:03AM -0800, Jesse Rosenthal wrote:
>>> Not sure, I've never built it on windows. But I think you can download
>>> the Haskell platform, and then it should be like for any other platform.
>>> 
>>> russurquhart1 <notifications@github.com> writes:
>>> 
>>> > I'm not sure if i do for my windows machine at work. Other than that, is there anything else needed to make an executable for windows? I don't have the windows sdk or anything like that.
>>> >
>>> >
>>> >
>>> > On Thu, Feb 19, 2015 at 06:29:30AM -0800, Jesse Rosenthal wrote:
>>> >> I don't know about the time frame for release. You can always test the
>>> >> dev version by building it -- do you have a haskell compiler?
>>> >> 
>>> >> russurquhart1 <notifications@github.com> writes:
>>> >> 
>>> >> > Is there a time frame for the release of this or is there a way we could test the dev version?
>>> >> >
>>> >> >
>>> >> > Thanks,
>>> >> >
>>> >> >
>>> >> > Russ
>>> >> >
>>> >> >
>>> >> > On Wed, Feb 18, 2015 at 10:10:32PM -0800, Jesse Rosenthal wrote:
>>> >> >> Just a note to add that # 3 above is now fixed in development version.
>>> >> >> 
>>> >> >> ---
>>> >> >> Reply to this email directly or view it on GitHub:
>>> >> >> https://github.com/jkr/pandoc/issues/6#issuecomment-75003792
>>> >> >
>>> >> >
>>> >> > ---
>>> >> > Reply to this email directly or view it on GitHub:
>>> >> > https://github.com/jkr/pandoc/issues/6#issuecomment-75058576
>>> >> 
>>> >> 
>>> >> ---
>>> >> Reply to this email directly or view it on GitHub:
>>> >> https://github.com/jkr/pandoc/issues/6#issuecomment-75060293
>>> >
>>> >
>>> > ---
>>> > Reply to this email directly or view it on GitHub:
>>> > https://github.com/jkr/pandoc/issues/6#issuecomment-75061412
>>> 
>>> 
>>> ---
>>> Reply to this email directly or view it on GitHub:
>>> https://github.com/jkr/pandoc/issues/6#issuecomment-75062539
>>
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/jkr/pandoc/issues/6#issuecomment-75063321
>
>
> ?
> Reply to this email directly or view it on GitHub.
> 
> 
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkr/pandoc/issues/6#issuecomment-75089124


?

**Comment by russurquhart1** [comment]
Well i haven't had any luck getting the dev src to compile. I loaded a new 64-bit Haskell compiler, but it keeps failing at the cabal install command.

So i guess i'll just have to wait until this gets to a released version!

Thanks for all your help!


Russ 
 
 

On 02/19/15, Jesse Rosenthal<notifications@github.com> wrote:
 
Always from jgm/pandoc. Mine is just there to store branches while I'm
switching computers, or to try stuff out.

russurquhart1 <notifications@github.com> writes:

> I was going to try it using git as mentioned in the INSTALL file. Should i get your dev from jkr/pandoc or from jgm/pandoc?
> 
> 
> 
> 
> On 02/19/15, Jesse Rosenthal<notifications@github.com> wrote:
> 
> I just noticed that in the pandoc source dir, there's a windows batch
> script called `make-windows-installer.bat`. Maybe that will work? 
>
> russurquhart1 <notifications@github.com> writes:
>
>> OK, i'll give it a try!
>>
>>
>> Thanks
>>
>>
>> Russ
>>
>>
>> On Thu, Feb 19, 2015 at 06:43:03AM -0800, Jesse Rosenthal wrote:
>>> Not sure, I've never built it on windows. But I think you can download
>>> the Haskell platform, and then it should be like for any other platform.
>>> 
>>> russurquhart1 <notifications@github.com> writes:
>>> 
>>> > I'm not sure if i do for my windows machine at work. Other than that, is there anything else needed to make an executable for windows? I don't have the windows sdk or anything like that.
>>> >
>>> >
>>> >
>>> > On Thu, Feb 19, 2015 at 06:29:30AM -0800, Jesse Rosenthal wrote:
>>> >> I don't know about the time frame for release. You can always test the
>>> >> dev version by building it -- do you have a haskell compiler?
>>> >> 
>>> >> russurquhart1 <notifications@github.com> writes:
>>> >> 
>>> >> > Is there a time frame for the release of this or is there a way we could test the dev version?
>>> >> >
>>> >> >
>>> >> > Thanks,
>>> >> >
>>> >> >
>>> >> > Russ
>>> >> >
>>> >> >
>>> >> > On Wed, Feb 18, 2015 at 10:10:32PM -0800, Jesse Rosenthal wrote:
>>> >> >> Just a note to add that # 3 above is now fixed in development version.
>>> >> >> 
>>> >> >> ---
>>> >> >> Reply to this email directly or view it on GitHub:
>>> >> >> https://github.com/jkr/pandoc/issues/6#issuecomment-75003792
>>> >> >
>>> >> >
>>> >> > ---
>>> >> > Reply to this email directly or view it on GitHub:
>>> >> > https://github.com/jkr/pandoc/issues/6#issuecomment-75058576
>>> >> 
>>> >> 
>>> >> ---
>>> >> Reply to this email directly or view it on GitHub:
>>> >> https://github.com/jkr/pandoc/issues/6#issuecomment-75060293
>>> >
>>> >
>>> > ---
>>> > Reply to this email directly or view it on GitHub:
>>> > https://github.com/jkr/pandoc/issues/6#issuecomment-75061412
>>> 
>>> 
>>> ---
>>> Reply to this email directly or view it on GitHub:
>>> https://github.com/jkr/pandoc/issues/6#issuecomment-75062539
>>
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/jkr/pandoc/issues/6#issuecomment-75063321
>
>
> ?
> Reply to this email directly or view it on GitHub.
> 
> 
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkr/pandoc/issues/6#issuecomment-75089124


?
